// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NestQuest.Model;

#nullable disable

namespace NestQuest.Migrations
{
    [DbContext(typeof(RealEstateContext))]
    [Migration("20250204171437_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NestQuest.Model.Client", b =>
                {
                    b.Property<int>("clientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clientId"));

                    b.Property<string>("Emai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InterestedPropId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumper")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clientId");

                    b.HasIndex("InterestedPropId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("NestQuest.Model.Owner", b =>
                {
                    b.Property<int>("ownerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ownerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ownerId1")
                        .HasColumnType("int");

                    b.HasKey("ownerId");

                    b.HasIndex("ownerId1");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("NestQuest.Model.ProperityType", b =>
                {
                    b.Property<int>("propTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("propTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("propTypeId");

                    b.ToTable("ProtectedTypes");
                });

            modelBuilder.Entity("NestQuest.Model.Properties", b =>
                {
                    b.Property<int>("propId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("propId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ownerId")
                        .HasColumnType("int");

                    b.Property<int?>("propTypeId")
                        .HasColumnType("int");

                    b.HasKey("propId");

                    b.HasIndex("ownerId");

                    b.HasIndex("propTypeId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("NestQuest.Model.Transaction", b =>
                {
                    b.Property<int>("TransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("NestQuest.Model.Client", b =>
                {
                    b.HasOne("NestQuest.Model.Properties", "InterestedProp")
                        .WithMany()
                        .HasForeignKey("InterestedPropId");

                    b.Navigation("InterestedProp");
                });

            modelBuilder.Entity("NestQuest.Model.Owner", b =>
                {
                    b.HasOne("NestQuest.Model.Owner", null)
                        .WithMany("Owners")
                        .HasForeignKey("ownerId1");
                });

            modelBuilder.Entity("NestQuest.Model.Properties", b =>
                {
                    b.HasOne("NestQuest.Model.Owner", "Owners")
                        .WithMany()
                        .HasForeignKey("ownerId");

                    b.HasOne("NestQuest.Model.ProperityType", "ProperityTypes")
                        .WithMany("properties")
                        .HasForeignKey("propTypeId");

                    b.Navigation("Owners");

                    b.Navigation("ProperityTypes");
                });

            modelBuilder.Entity("NestQuest.Model.Transaction", b =>
                {
                    b.HasOne("NestQuest.Model.Client", "Clients")
                        .WithMany("Transactions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NestQuest.Model.Properties", "Properties")
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clients");

                    b.Navigation("Properties");
                });

            modelBuilder.Entity("NestQuest.Model.Client", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("NestQuest.Model.Owner", b =>
                {
                    b.Navigation("Owners");
                });

            modelBuilder.Entity("NestQuest.Model.ProperityType", b =>
                {
                    b.Navigation("properties");
                });
#pragma warning restore 612, 618
        }
    }
}
